### ISSUE TITLE
希望增加Server酱推送功能

### ISSUE THREAD

**Issue by Crazyguy2020** [Secriy/CloudMusic-LevelUp#1]
希望增加Server酱推送功能

**Comment by Secriy** [comment]
你好，已经应你的要求，增加了该功能，使用方式已添加到README。请测试使用，如有问题请提出，感激不尽。

**Comment by Secriy** [comment]
你好，已经应你的要求增加了该功能，使用方式在README中。需重新fork仓库使用新版，在Secrets添加SCKEY字段即可。如有问题，烦请告知。

**Comment by Secriy** [comment]
> 希望增加Server酱推送功能

你好，已经应你的要求增加了该功能，使用方式在README中。需重新fork仓库使用新版，在Secrets添加SCKEY字段即可。如有问题，烦请告知。
