### ISSUE TITLE
代码执行到run script概率性发生错误

### ISSUE THREAD

**Issue by LinnyR** [Secriy/CloudMusic-LevelUp#11]
![1](https://user-images.githubusercontent.com/38827394/107599870-fbaad500-6c5c-11eb-9058-0e01f56fe11d.png)
![2](https://user-images.githubusercontent.com/38827394/107599874-fea5c580-6c5c-11eb-9c8b-a6b402a402b5.png)
![3](https://user-images.githubusercontent.com/38827394/107599879-006f8900-6c5d-11eb-90a3-eee8ddae35e2.png)
![4](https://user-images.githubusercontent.com/38827394/107599882-01a0b600-6c5d-11eb-82fc-c5d491cb0eac.png)
请问大佬是什么原因造成的

**Comment by Secriy** [comment]
@LinnyR 你好，我看了下你的Actions执行记录，发现总共有两次错误。第一次错误是由于脚本使用了Server酱，而当天该服务正在进行升级所以无法使用。第二次错误则是GitHub Actions执行出错，暂不知是什么原因但是与脚本本身无关，并且这种错误并不常见，无需在意。

**Comment by LinnyR** [comment]
好的 谢谢您的解答
