### ISSUE TITLE
怎么修改实现多次执行，每天两次感觉不够，有时候刷不够300首

### ISSUE THREAD

**Issue by SR810** [Secriy/CloudMusic-LevelUp#13]

**Comment by Secriy** [comment]
@SR810 请对照README注意事项前面的多次执行方法，只需要增加一个时间即可

**Comment by Secriy** [comment]
> @SR810 请对照README注意事项前面的多次执行方法，只需要增加一个时间即可

比如"0 4/8/16 * * *"就是执行三次，数字代表UTC时间，转换为北京时间需要加8，即12点、16点、24点

**Comment by SR810** [comment]
好的，谢谢
