### ISSUE TITLE
定时执行未成功

### ISSUE THREAD

**Issue by luv1029** [Secriy/CloudMusic-LevelUp#17]
我设置了UTC时间17/18点执行（北京时间凌晨1点和2点），但是Server并没有给我推送。但是我测试Server是正常工作的。还有UTC时间好像只能设置两个，我改成17/18/19就报错了。

**Comment by Secriy** [comment]
你好，我这边看到你的Actions执行存在参数报错，请先检查下你设置的Secret参数（账号、密码、Server酱密钥等）是否正确。另外由于Server酱近期的更新，需要访问Server酱官网进行推送配置，如果不进行正确的配置无法推送。

**Comment by Secriy** [comment]
@luv1029 你好，我这边看到你的Actions执行存在参数报错，请先检查下你设置的Secret参数（账号、密码、Server酱密钥等）是否正确。另外由于Server酱近期的更新，需要访问Server酱官网进行推送配置，如果不进行正确的配置无法推送。
