### ISSUE TITLE
是不是接口挂掉了

### ISSUE THREAD

**Issue by adil-zhang** [Secriy/CloudMusic-LevelUp#18]
每天都在跑，但是数量一点没涨

**Comment by Secriy** [comment]
@adil-zhang 你好，我这边看到你的执行记录最近两天都有增长。由于脚本只会刷网易云音乐推荐的歌单，存在网易云每天推荐已经听过的音乐的可能，因此某几天出现不增长是有可能的，如果觉得不妥，可以每天多次执行脚本，参照[多次执行](https://github.com/Secriy/CloudMusic-LevelUp#5-%E5%A4%9A%E6%AC%A1%E6%89%A7%E8%A1%8C%E5%8F%AF%E9%80%89)。

**Comment by adil-zhang** [comment]
好的谢谢，慢慢刷吧。
