### ISSUE TITLE
【功能请求】能否增加一个设置刷歌数量的Secret变量

### ISSUE THREAD

**Issue by Lssg97** [Secriy/CloudMusic-LevelUp#22]
目前已经Fork了仓库但是还没下定决心开始使用。由于担心使用后每日的随机刷歌导致日推歌单出现喜好误判，所以希望能增加一个设置刷歌数量的Secret变量。这样设置为 `0` 后可以关闭刷歌功能。或者设置一个是否刷歌的布尔变量也可以。

（顺带附加另一个无关紧要的功能请求，能不能增加对Telegram推送的支持呢？）

**Comment by Secriy** [comment]
@Lssg97 你好，每日刷歌的歌单来自网易云推荐，基本不会影响推荐风格的改变。另外，这个GitHub Actions可以随时手动开启/关闭，如果不需要的话直接在Actions选项里手动关闭就好。最后关于Telegram的推送我会考虑，之后会加入。

**Comment by Secriy** [comment]
![image](https://user-images.githubusercontent.com/41107263/111297929-28ea0900-8689-11eb-885b-7afe5f465831.png)

**Comment by Lssg97** [comment]
好吧，也许我没有说清楚。其实我只想要签到功能，而放弃刷歌功能。可是在Github里没有找到只签到的仓库

**Comment by Lssg97** [comment]
@Secriy 好吧，也许我没有说清楚。其实我只想要签到功能，而放弃刷歌功能。可是在Github里没有找到只签到的仓库

**Comment by Secriy** [comment]
@Lssg97 这样的话其实更好办，直接把action.py的第126行注释掉就行了，刷歌就不会执行了。

**Comment by Secriy** [comment]
@Lssg97 这样的话其实更好办，直接把action.py的第126行注释掉就行了，刷歌就不会执行了。这样操作甚至比删除/创建Secret还要快不少。

**Comment by Lssg97** [comment]
哦哦哦太妙了 学会了

**Comment by Secriy** [comment]
@Lssg97 目前Telegram推送已经更新
