### ISSUE TITLE
能否添加Telegram和Discord推送

### ISSUE THREAD

**Issue by jiayouba233** [Secriy/CloudMusic-LevelUp#23]
Rt

**Comment by jiayouba233** [comment]
本项目已Star

**Comment by Secriy** [comment]
@jiayouba233 您好，目前已经更新Telegram推送方式，请自行获取所需要的Telegram Bot和oken，以及账号的Chat ID。创建方法网络上有很多教程可以参考，这里说一下Chat ID的获取：访问https://api.telegram.org/bot**Token**/getUpdates

**Comment by Secriy** [comment]
@jiayouba233 你好，目前已经更新Telegram推送方式，请自行获取所需要的Telegram Bot和Token，以及账号的Chat ID。创建方法网络上有很多教程可以参考，这里说一下Chat ID的获取：
1.  访问https://api.telegram.org/bot**Token**/getUpdates（将Token替换为Bot的Token）
2.  发送任意消息给机器人
3.  再次访问上述链接，查看新增的对话记录，得到Chat ID

**Comment by Secriy** [comment]
@jiayouba233 另外，由于本人没有使用过Discord，暂不了解推送的方式，或许之后会加入，十分遗憾。
