### ISSUE TITLE
增加Bork推送 

### ISSUE THREAD

**Issue by Saxon-Sun** [Secriy/CloudMusic-LevelUp#24]
> data = {
    "title": "网易云打卡脚本",
    "body": text
}
headers = {'Content-Type': 'application/json;charset=utf-8'}
url = 'https://api.day.app/{Barkkey}/?isArchive={Barksave}'
ret = requests.post(url, json = data, headers = headers)
state=json.loads(ret.text)
print(state)

我这边写好了通知代码了 
麻烦检查修改把他合并一下
Barkkey变量意思是Token
Barksave变量为1保留通知在手机  其他变量不存在通知在手机
就两个变量

**Comment by Saxon-Sun** [comment]
如果没法测试的话 可以创建个分支 补齐后我这边再测试一下

**Comment by Secriy** [comment]
@Saxon-Sun 你好，功能已经加入，请参照[Bark](https://github.com/Secriy/CloudMusic-LevelUp#bark-%E6%8E%A8%E9%80%81)进行配置，GitHub Actions部署方式也在README中进行了更新，经测试可用，如果有问题请提issue，感谢支持。

**Comment by Secriy** [comment]
@Saxon-Sun 另由于目前使用的变量很多，为了避免命令行参数过于复杂，如有需要请自行修改isArchive参数，位于action.py 314行。

**Comment by Saxon-Sun** [comment]
@Secriy 嗯 了解 感谢加入
