### ISSUE TITLE
关于server酱SCKEY写上去无效问题

### ISSUE THREAD

**Issue by nnonnn** [Secriy/CloudMusic-LevelUp#26]
如标题

SCKEY写上去 微信不推送信息，秘钥无问题

**Comment by Secriy** [comment]
@nnonnn 你好，根据你的执行报错`{"message":"[AUTH]用户不存在或者权限不足","code":40001,"info":"用户不存在或者权限不足","args":[null]} `判断可能是Server酱配置错误，请访问[Server酱官网](https://sct.ftqq.com/)，在消息通道选项内进行配置。另外Server酱现在已经更新为Turbo版，需要重新配置密钥等信息。
