### ISSUE TITLE
TypeError: str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by DerrickBu** [Secriy/CloudMusic-LevelUp#29]
Thanks for bringing this project open source!

Met an error when I ran the script using command

python action.py 1xxxxxcc 9xxxxxxxxxxxxxxb

Traceback (most recent call last):
  File "action.py", line 295, in <module>
    app = CloudMusic(info["phone"], info["password"])
  File "action.py", line 151, in __init__
    "rememberLogin": "true"
  File "action.py", line 134, in encrypt
    sec_key = create_secret_key(16)
  File "action.py", line 64, in create_secret_key
    return str(binascii.hexlify(os.urandom(size))[:16], encoding="utf-8")

**Comment by Secriy** [comment]
@DerrickBu Hi, I'm noticed that your GitHub Actions already worked. Have you solved this problem? Or that if you haven't solved it, check out your input arguments first. Thanks for issue.

**Comment by DerrickBu** [comment]
@Secriy Thanks for the response! Yes, my Action workflow succeeded, but I still cannot run the script manually. I tried to debug into that one but didn't find anything suspicious. The command I ran was exactly like `python action.py 1xxxxxcc 9xxxxxxxxxxxxxxb` as I mentioned above.

Could you please help check with this?

**Comment by Secriy** [comment]
@DerrickBu Hi，it might seems like you are using Python2 with your error messages, maybe you can try Python3 instead of Python2. Like `python3 [phone_number] [password_md5]`.

**Comment by Secriy** [comment]
@DerrickBu It might seems like you are using Python2, maybe you can try Python3 instead of Python2. With command like `python3 [phone_number] [password_md5]`.

**Comment by Secriy** [comment]
@DerrickBu Hello, have you solved this problem? If done, please reply to me and close that issue.

**Comment by DerrickBu** [comment]
@Secriy I think it was due to the chaos python environment on my laptop, feel free to close the issue. Thank you for the help!
