### ISSUE TITLE
可以加企业微信推送么？

### ISSUE THREAD

**Issue by ajmhsa** [Secriy/CloudMusic-LevelUp#30]
api文档：https://work.weixin.qq.com/api/doc/90000/90135/90236
微信官方的，使用很方便，普通微信也能接收到消息，不需要下载企业微信。

**Comment by Secriy** [comment]
@ajmhsa 您好，脚本提供了 Server 酱推送，可以使用该服务调用企业微信通道推送，详情请参考[Server 酱官网](https://sct.ftqq.com/)，登录后在消息通道内选择企业微信通道即可。

**Comment by ajmhsa** [comment]
> @ajmhsa，特性服务器机舱，机舱机舱，机要机，以"小"为"服务器服务器前人卡多克 · 德金 · 特约 · 特约 · 德金 · 德金

server酱免费额度太少了，每天只有5次。并且7天好像就会过期，企业微信就没有这些限制。

**Comment by Secriy** [comment]
@ajmhsa 会考虑您的需求，请等待脚本更新，感谢支持。

**Comment by Secriy** [comment]
@ajmhsa 您好，脚本已经更新企业微信推送，请自行测试，如有问题烦请及时提issue，谢谢。

**Comment by ajmhsa** [comment]
> @ajmhsa 您好，脚本已经更新企业微信推送，请自行测试，如有问题烦请及时提issue，谢谢。

感谢，已测试，可以正常推送。
