### ISSUE TITLE
刷听歌量 不显示数量是什么问题？

### ISSUE THREAD

**Issue by knowledgeablelmh** [Secriy/CloudMusic-LevelUp#33]
![QQ截图20210422012504](https://user-images.githubusercontent.com/49005295/115595544-a1d42480-a309-11eb-9f80-1864b3ede728.png)

**Comment by Secriy** [comment]
@knowledgeablelmh 你好，由于脚本每天选取推荐歌单进行刷量，当歌单足够大时脚本只会选取其中几百首，因此大多数情况下每天都是固定的数量，无需进行显示。日后可能会增加有效刷歌量的显示，目前还未实现。

**Comment by knowledgeablelmh** [comment]
谢谢  ，是不是不加歌单也可以？

**Comment by knowledgeablelmh** [comment]
还有就是多账号应该怎么写？

**Comment by Secriy** [comment]
@knowledgeablelmh 是的完全可以不添加歌单，默认就会使用网易云音乐推荐的歌单了。另外我个人并未考虑多账号的情况，因为感觉不是很有必要，如果你有需要的话我可以增加这个功能。

**Comment by knowledgeablelmh** [comment]
感谢！！！   希望可以加一个吧 ，身边朋友 有的也需要

**Comment by Secriy** [comment]
@knowledgeablelmh 你好，已经更新多账号任务功能，请修改 Secret 的手机号和密码字段，改为以英文逗号分隔的多个参数，具体可以参照 README 文档。如果脚本存在问题，烦请提出 issue，十分感谢。
