### ISSUE TITLE
请求增加pushplus推送方式

### ISSUE THREAD

**Issue by misaka-h** [Secriy/CloudMusic-LevelUp#34]
severchan将在四月底更新至付费通道（每日5条以上消息需捐赠），请求增加pushplus推送：[pushplus官网](http://www.pushplus.plus/)

**Comment by Secriy** [comment]
@misaka-h 近期会加入，感谢支持。

**Comment by Secriy** [comment]
@misaka-h 你好，脚本已经增加pushplus推送，请参考README文件进行操作。

**Comment by misaka-h** [comment]
> @misaka-h 你好，脚本已经增加pushplus推送，请参考README文件进行操作。

辛苦了，非常感谢！
