### ISSUE TITLE
请问账户禁止操作该怎样启动

### ISSUE THREAD

**Issue by ghost** [Secriy/CloudMusic-LevelUp#35]
Actions are currently disabled for your account. Please reach out to GitHub Support for assistance.
![微信截图_20210501095751](https://user-images.githubusercontent.com/49005295/116767589-b6c85a80-aa63-11eb-8bca-acb25ee78cf7.png)

**Comment by Secriy** [comment]
@knowledgeablelmh 您好，请按报错信息提供的链接联系GitHub客服支持询问，暂不知是什么原因，可能和你的GitHub账户有关。

**Comment by knowledgeablelmh** [comment]
好的 ，谢谢

**Comment by mrtseng** [comment]
> @knowledgeablelmh 您好，请按报错信息提供的链接联系GitHub客服支持询问，暂不知是什么原因，可能和你的GitHub账户有关。

账户禁用于近期的挖矿事件有关，github目前对action自动运行的严查。是否可以增加腾讯云函数部署方式？

**Comment by Secriy** [comment]
@mrtseng 好的，近期会加入
