### ISSUE TITLE
请教下自定义歌单号怎么获得

### ISSUE THREAD

**Issue by dh0608** [Secriy/CloudMusic-LevelUp#36]
发现playlist里有一些歌单号只能使用一次后就不更新了，想问下如果自己自定义歌单得话，歌单号在哪里看呢

**Comment by Secriy** [comment]
@dh0608 你好，手机端 分享-复制链接 得到歌单的链接地址，路径的第一串数字就是歌单的id，如`http://music.163.com/playlist/741934630`其中741934630就是id。

**Comment by Secriy** [comment]
@dh0608 如果是要实现刷歌的话建议清空playlist，这样会使用网易云音乐每天推荐的不同歌曲。

**Comment by dh0608** [comment]
明白了，这也验证了我得猜测，感谢回复

**Comment by dh0608** [comment]
> @dh0608 如果是要实现刷歌的话建议清空playlist，这样会使用网易云音乐每天推荐的不同歌曲。

原来如此，这个功能不错
