### ISSUE TITLE
Telegram Bot 推送貌似失效了

### ISSUE THREAD

**Issue by Lssg97** [Secriy/CloudMusic-LevelUp#37]
自最近一次提交后，Telegram推送貌似失效了。已经按照最新的自述文件设置了新的变量名，也按照所说的格式依次填写了token和id。可是并没有消息推送。

**Comment by Lssg97** [comment]
这是工作流程里显示的信息：

![image](https://user-images.githubusercontent.com/47817993/117546303-5c7b5b00-b05c-11eb-9900-2dc5276fc887.jpeg)

**Comment by Secriy** [comment]
@Lssg97 您好，已经修复，十分感谢反馈
