### ISSUE TITLE
太难了球球大佬来个傻瓜式

### ISSUE THREAD

**Issue by AKAmisaki** [Secriy/CloudMusic-LevelUp#38]
秋梨膏谢谢大佬

**Comment by Secriy** [comment]
@AKAmisaki 啊这你把项目fork之后找到自己fork的仓库,Settings-Secret,按要求添加账号密码什么的就行了,最后再点Actions启动自动执行.

**Comment by AKAmisaki** [comment]
> @AKAmisaki啊这你把项目fork之后找到自己的fork的仓库，设置秘密，按要求添加账号密码什么的就行了，最后再点动作启动自动执行。

 return {
        "13307018439": args.phone,
        "azxc79681": args.password,
        "sc_key": args.sc_key,
        "tg_bot_key": args.tg_bot_key,
        "bark_key": args.bark_key,
        "wecom_key": args.wecom_key,
        "push_plus_key": args.push_plus_key,
    }
我只要改这一段是不是就可以了？？？
我改了以后显示错误为2

**Comment by Secriy** [comment]
@AKAmisaki 额, 你最好不要改脚本, 要是有时间, 你可以邮箱发我你QQ帮你弄.

**Comment by AKAmisaki** [comment]
> @AKAmisaki额，你最好不要改脚本，要是有时间，你可以邮箱发我你QQ帮你弄。
> [secriyal@gmail.com](mailto:secriyal@gmail.com)

TAT 想预习一下大一的py 我还是自己琢磨吧谢谢大佬

**Comment by Secriy** [comment]
@AKAmisaki 学习没问题,主要是你改脚本会泄露个人信息的.

**Comment by AKAmisaki** [comment]
> @AKAmisaki学习没问题，主要是你改脚本会附属个人信息的。

哦哦我知道了太谢谢了
