### ISSUE TITLE
自定义歌单 刷歌量极低

### ISSUE THREAD

**Issue by EYW-015** [Secriy/CloudMusic-LevelUp#39]
个人测试情况：

### 2.playlist指定为自定义歌单，分别测试了以下4种情况

2.1 喜爱歌单 1800首
2.2 自建歌单 2400首
2.3 他人创建歌单170首
2.4 多重歌单80+170+1700首

运行脚本成功后等待2分钟，查看升级所需歌量，每次运行仅刷2~15首

**Comment by Secriy** [comment]
@EYW-015 这个自定义歌单的功能对于刷听歌量升级的用户来说是不建议使用的，我也改成了默认不使用，因为需要修改歌单本身就麻烦，另外你自定义的歌单如果里面都是以前听过的曲子是没什么作用的。

**Comment by EYW-015** [comment]
好的，了解，感谢您的回答
