### ISSUE TITLE
你好，请问显示刷歌成功，但是APP里数量没有减少是什么原因？

### ISSUE THREAD

**Issue by knowledgeablelmh** [Secriy/CloudMusic-LevelUp#40]
请问显示刷歌成功，但是APP里数量没有减少是什么原因？

**Comment by Secriy** [comment]
@knowledgeablelmh 你把playlist.txt清空了，自定义歌单的情况下不使用网易云音乐推荐的随机歌单，这些歌之前刷过了就不会再记录听歌量了。

**Comment by knowledgeablelmh** [comment]
我把文件里的歌单删除运行会报错，Error: Process completed with exit code 1.   请问是什么意思，有联系方式吗方便交流一下

**Comment by Secriy** [comment]
@knowledgeablelmh 最简单的方法是删除仓库重新Fork就好了，新版修复了很多东西，修改了一些操作方式

**Comment by knowledgeablelmh** [comment]
好的，谢谢我试试

**Comment by knowledgeablelmh** [comment]
大佬好郁闷啊   复刻的就可以运行，自己下载你源码上传的就不行。。。。

**Comment by Secriy** [comment]
@knowledgeablelmh 你仔细检查下二者的差异吧，我也不清楚你是怎么操作的，你要是想本地修改项目，直接clone自己fork的往上修改就可以了，不需要重头开始上传。

**Comment by knowledgeablelmh** [comment]
就是   playlist.txt  这个文件的问题   你库里复刻过来的是0字节   我上传空文件上传不了   手动添加的创建完就是1字节
