### ISSUE TITLE
刷音乐播放量是不是无效了

### ISSUE THREAD

**Issue by litocc** [Secriy/CloudMusic-LevelUp#43]
如题，每次刷完播放量后，在手机上看发现没有变化，或者有变化但并未达到规定数值

**Comment by Secriy** [comment]
@Secriy 您好，请检查脚本是否为新版，另外请不要使用自定义歌单功能。

**Comment by litocc** [comment]
> @Secriy 您好，请检查脚本是否为新版，另外请不要使用自定义歌单功能。

确定是最新版的脚本，还有就是现在网易云好像规定每天最多只能刷300首歌。

![QQ截图20210604234049](https://user-images.githubusercontent.com/68491603/120827911-85750a00-c58e-11eb-9ff9-e62923c735b7.jpg)

**Comment by Secriy** [comment]
@litocc 300首的限制在README文档注意事项中有提到，这是正常的，只要每天刷够300首就可以了。受限于网易云音乐的推荐机制，有很多时候是无法刷满的，可以参考说明文档每天多次执行。
