### ISSUE TITLE
希望可以手动选择手机的country code

### ISSUE THREAD

**Issue by ShinkaiMakoto** [Secriy/CloudMusic-LevelUp#44]
country code默认+86，对于国外号码关联的很伤啊啊啊
希望可以手动更改（比如说用secre ts）QAQ

**Comment by Secriy** [comment]
@ShinkaiMakoto 您好,已经更新国外手机号登录功能,请将手机号字段使用新格式(`区号+手机号`，如`852+12343123`)填写,具体参考[执行脚本](https://github.com/Secriy/CloudMusic-LevelUp#%E6%89%A7%E8%A1%8C%E8%84%9A%E6%9C%AC)

**Comment by ShinkaiMakoto** [comment]
用actions测试 可以正常运行
感谢
