### ISSUE TITLE
每次显示刷了300首，实际上就刷了几首到几十首

### ISSUE THREAD

**Issue by Sakananb** [Secriy/CloudMusic-LevelUp#47]
![image](https://user-images.githubusercontent.com/80612444/122906832-259ba300-d385-11eb-83f3-063d6ec6f5ef.png)

**Comment by Secriy** [comment]
@Sakananb 您好，显示的刷歌量是程序从推荐歌单中截取的固定数量，而非实际刷歌的数量，刚刚对脚本做了修改，选用个人收藏的歌单进行刷歌，请更新下脚本并尝试收藏一些新的歌单，如果还有此问题烦请告知。
