### ISSUE TITLE
请问TG不能推送是什么问题？

### ISSUE THREAD

**Issue by dcitay** [Secriy/CloudMusic-LevelUp#48]
Starting new HTTPS connection (1): api.telegram.org:443

HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1/sendMessage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7deed860b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by Secriy** [comment]
@dcitay 你好，请问是本地执行还是 GitHub Actions 部署？Telegram 在国内被墙了，本地执行必须要走代理才能访问，建议在 GitHub Actions 中部署使用 Telegram Bot 推送。

**Comment by dcitay** [comment]
> @dcitay 你好，请问是本地执行还是 GitHub Actions 部署？Telegram 在国内被墙了，本地执行必须要走代理才能访问，建议在 GitHub Actions 中部署使用 Telegram Bot 推送。

噢噢，我是在腾讯云函数部署的，忘了这回事了.....没事了
