### ISSUE TITLE
请问账号必须要是手机账号吗？邮箱账号是否支持？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [Secriy/CloudMusic-LevelUp#49]

**Comment by Secriy** [comment]
@Yakumo-Yukari 你好，暂不支持邮箱登录，如果有需要的话我去看看能不能加入这个登录方式，请稍等。

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari 你好，暂不支持邮箱登录，如果有需要的话我去看看能不能加入这个登录方式，请稍等。

麻烦你了

**Comment by matocool** [comment]
不是都要绑定手机号吗。。。何必邮箱呢。。

**Comment by Yakumo-Yukari** [comment]
> 不是都要绑定手机号吗。。。何必邮箱呢。。
谁说都要绑定手机的？？？网易邮箱都是直接登录的哦

**Comment by Secriy** [comment]
@Yakumo-Yukari 对你手动设置密码之后就能用手机号登录了。
