### ISSUE TITLE
关于单次刷歌曲量不够的建议

### ISSUE THREAD

**Issue by misaka-h** [Secriy/CloudMusic-LevelUp#5]
一天刷两次歌可能可以解决问题。
即在时间表达式中改为 “0 4/12 * * * ”，表示12点和20点各刷一次。

**Comment by Secriy** [comment]
多谢建议，为了方便查看每天的运行情况并防止Server酱微信推送打扰，我只设置了一天一次执行，现在打算在README里说明方便用户按需设置。
