### ISSUE TITLE
大佬 反馈点小建议哈

### ISSUE THREAD

**Issue by matocool** [Secriy/CloudMusic-LevelUp#50]
1、刷听歌量成功，共500首  这个首先最多300   500这个是不是要改改、、而且不管刷成功多少首他都是提示500..希望能获取一次之前的次数，然后再刷完之后减去之前的次数得到正确的数

2、实测一次刷歌只能123左右，只能用一天多次触发来执行，隔壁可以通过修改里代码里面的次数来修改听歌次数，这样一天就不用设置多次并发了。  可否指点下 哪个文件代码第几行呢？

3、大佬的云函数需要API吗？如果要，是不是在用大佬的API呢

4、有没有兴趣开发酷狗在线时长项目的兴趣。。

谢谢大佬了。。。小白路过随便说说 别喷我

**Comment by matocool** [comment]
还有个问题，，，


sc_key  我填入了涡轮版的SendKey  ，任务已经执行完毕但是手机并未得到推送。然后我测试下 key正常，可以正常推送到手机。

于是我想，是不是还要执行另一个命令。（如下）
--------------------------------------------------------------------------------------------------------------------------------
python action.py 1xx014x4636 1xxx2xx324x65fx6xb22846ea8xcx0x7 -s SSS111111T111112f3e421

按照该格式 【我 在IDE 中打开一个终端 】并 输入这段代码 

结果报错：[Errno 2] No such file or directory

--------------------------------------------------------------------------------------------------------------------------------

我又想了下试试别的路径，然后在action.py 右键选择路径以及相对路径均报错。

src/README

/usr/local/var/functions/ap-shanghai/lam-q94ar7dy/XXXXXXXXXXXXXX/src/action.py 


结果报错：SyntaxError: invalid syntax

--------------------------------------------------------------------------------------------------------------------------------
求解，谢谢

**Comment by Secriy** [comment]
@matocool 
1. 500的量是指从歌单池里的所有歌曲中随机选取的量，因为会有很多已经听过的歌曲所以设置稍大一点能增加有效的量。 关于获取实际刷量的反馈，因为网易云更新并不实时所以之前偷懒给这个功能删除了，之后可能会加入。

2. 关于让脚本多次执行，这是因为一次性执行多次的话可能会导致执行时间稍久，有必要的话也可以让它一次性执行完。实际有效的数量不高是因为网易云推荐的音乐很多都重复了，目前最新的脚本使用的策略是把用户收藏的歌单加入歌单池，可以尝试收藏一些没怎么听过的的大歌单。刷量目前是比较保守因为可能会影响用户的听歌喜好。这些都可以解决。

3. 云函数部署实际上就是执行一下脚本，没有调用别人的API，和GitHub Actions没有差别。

4. 关于酷狗不太了解，也不清楚需求是不是很普遍，可以沟通一下，联系方式在READ ME中。

**Comment by Secriy** [comment]
@matocool 目前脚本已经更新，修改331行的数字可以改变任务执行次数。关于你后面的报错由于相关错误信息并不完整，可以先更新下脚本并检查下Server Chan的推送通道，如果还存在问题请吧相关错误完整贴上来。

**Comment by matocool** [comment]
> @matocool 目前脚本已经更新，修改331行的数字可以改变任务执行次数。关于你后面的报错由于相关错误信息并不完整，可以先更新下脚本并检查下Server Chan的推送通道，如果还存在问题请把相关错误完整贴上来。

谢谢大佬，我先去试试

**Comment by matocool** [comment]
Starting new HTTPS connection (1): sctapi.ftqq.com:443

https://sctapi.ftqq.com:443 "POST /S.send HTTP/1.1" 500 189

ServerChan: {"message":"[AUTH]\u7528\u6237\u4e0d\u5b58\u5728\u6216\u8005\u6743\u9650\u4e0d\u8db3","code":40001,"info":"\u7528\u6237\u4e0d\u5b58\u5728\u6216\u8005\u6743\u9650\u4e0d\u8db3","args":[null]}

**Comment by matocool** [comment]
> @matocool 目前脚本已经更新，修改331行的数字可以改变任务执行次数。关于你后面的报错由于相关错误信息并不完整，可以先更新下脚本并检查下Server Chan的推送通道，如果还存在问题请把相关错误完整贴上来。

![1](https://user-images.githubusercontent.com/83129369/124401623-eeea6300-dd5c-11eb-8c06-325ad27f5868.png)

**Comment by Secriy** [comment]
@matocool 现在变成333行了，就是range()内的数字
