### ISSUE TITLE
云函数企业微信推送问题

### ISSUE THREAD

**Issue by vay1314** [Secriy/CloudMusic-LevelUp#51]
请教云函数企业微信推送，是在index.py配置wecom_key项，格式为“企业ID 应用ID 应用Secrets”吗？我这样配置后，最后报以下错误
Starting new HTTPS connection (1): qyapi.weixin.qq.com:443
https://qyapi.weixin.qq.com:443 "GET /cgi-bin/gettoken?corpid=w&corpsecret=e HTTP/1.1" 200 191
'access_token'

**Comment by matocool** [comment]
我推送也遇到了问题

**Comment by Secriy** [comment]
配置格式无误，我这边也没有发现问题，请多次测试下看看是否是100%会出现的问题，另外本地测试下脚本有无问题。

**Comment by Secriy** [comment]
@vay1314 您好，新的脚本已经修复了该问题，请参照说明进行修改，十分抱歉。
