### ISSUE TITLE
云函数自定义歌单问题

### ISSUE THREAD

**Issue by w926** [Secriy/CloudMusic-LevelUp#52]
为什么在同级目录下创建了歌单id的文本，运行之后并不会刷新歌单的播放量，但不会报错

**Comment by Secriy** [comment]
@w926 额这个自定义歌单功能已经取消了，因为用来刷歌根本没有自动化，现在可以收藏一些歌单来添加到歌单池。

**Comment by w926** [comment]
好的，谢谢，已经了解到了

**Comment by w926** [comment]
> @w926额这个自定义歌单功能已经取消了，因为刷歌根本没有自动化，现在可以收藏一些歌单来添加到歌单池。

好的，谢谢
