### ISSUE TITLE
MD5加密登录问题

### ISSUE THREAD

**Issue by VwEl** [Secriy/CloudMusic-LevelUp#53]
用 32 位小加密的MD5登录就会报：登录失败: -460
用明文则不会出现这种问题

**Comment by Secriy** [comment]
@VwEl 您好我这边无法复现您的问题，请检查下最新的代码能否解决问题，如果仍存在问题可以沟通解决。

**Comment by VwEl** [comment]
> 
> 
> @VwEl 您好我这边无法复现您的问题，请检查下最新的代码能否解决问题，如果仍存在问题可以沟通解决。

感谢回复！
最近才有空，今天更新到最新的代码后解决了此问题。但是不知道为什么index.py内的action.task_pool(infos)要修改成action.tasks_pool(infos)才能成功运行了
