### ISSUE TITLE
关于action执行失败的问题

### ISSUE THREAD

**Issue by zengjiahe** [Secriy/CloudMusic-LevelUp#54]
我按照自述文件进行配置，在secret中正确填写了手机号和明文密码，运行失败。后使用md5 32位小写仍运行失败。经检查手机号密码正确。报错代码如下action.py: error: argument -t: expected 2 arguments
Error: Process completed with exit code 2.感谢您在百忙之中阅览我的问题

**Comment by Secriy** [comment]
@zengjiahe 根据报错信息，是因为你使用了`-t`参数指定Telegram Bot推送，但是要求两个参数，你可能只指定了其一，请根据README文档修改参数值。

**Comment by Secriy** [comment]
@zengjiahe 您好，如果是腾讯云函数部署出现的问题，这是脚本的bug，请更新到最新的脚本并参照说明进行操作。
