### ISSUE TITLE
大佬，我提一个小小的建议哈

### ISSUE THREAD

**Issue by matocool** [Secriy/CloudMusic-LevelUp#55]
关于之前我提过推送的问题

"sc_key": ["SCT4XXXXXXXXXXXXXXXfO"],

我之前测试错误，后来测试要加上[]才有用。。。因为 ID  以及 MD5 那些没有用上这个符号。。惯性思维自然而然会把括号给删掉了

用腾讯云函数是不用输入         python action.py [手机号] [32位MD5密码加密值] -s [SendKey]

----------------------------------------------------------------------------------------------------------------------
还有如果使用server酱推送的话，我们能不能在标题那边改下，更加人性化。  目前的标题名字【网易云打卡】。

咱们可否改成【网易云今日已打卡，累计播放XXXX首】  这样就不用点进去查看详情，用今天的播放对比昨日的播放，就可以很明显看到是否成功以及增加的数量~

顺便问下不知道目前技术能不能做到自动拾取云贝？

只是提个建议哈，，大佬蛮看看。

**Comment by Secriy** [comment]
@matocool 你提到的错误，脚本前几天已经修复了并更新了部署文档。腾讯云函数部署时只需要按照说明执行相关操作，不需要手动执行命令。
