### ISSUE TITLE
pushplus方式接口链接有错误

### ISSUE THREAD

**Issue by WeszTx** [Secriy/CloudMusic-LevelUp#58]
pushplus方式接口链接有错误（136行），应该修改为：
`url = "http://pushplus.hxtrip.com/send?token={0}&title={1}&content={2}&template={3}".format(`

**Comment by Secriy** [comment]
您好，据我搜索，您提供的接口是pushplus的旧服务接口，建议转到新的pushplus官网地址。
![image](https://user-images.githubusercontent.com/41107263/125902902-814f69db-4265-4315-90b8-638b92cd85e0.png)

**Comment by WeszTx** [comment]
好的谢谢知道了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月16日(星期五) 下午2:35
收件人: ***@***.***&gt;; 
抄送: "李涛"<863253431@QQ.COM&gt;; ***@***.***&gt;; 
主题: Re: [Secriy/CloudMusic-LevelUp] pushplus方式接口链接有错误 (#58)





 
您好，据我搜索，您提供的接口是pushplus的旧服务接口，建议转到新的pushplus官网地址。
 
 
&mdash;
