### ISSUE TITLE
现在可以登陆，但是听歌量刷不上去

### ISSUE THREAD

**Issue by nashgoo** [Secriy/CloudMusic-LevelUp#59]
听歌量无论如何刷不上去，每次执行后剩余歌曲量总是保持不变，请问是歌单的问题吗？

**Comment by Secriy** [comment]
@nashgoo 您好，你使用的是自定义歌单，是旧版脚本提供的功能，现在已经没有了，使用这个之后之后反复地听`playlist.txt`文件中的歌曲，听过的歌曲不再累计听歌量，请将你的fork仓库强制更新到我仓库的最新版本。

**Comment by Secriy** [comment]
@nashgoo 可以使用GitHub提供的Fetch Upstream功能在网页端更新脚本。

**Comment by nashgoo** [comment]
> @nashgoo 可以使用GitHub提供的Fetch Upstream功能在网页端更新脚本。

搞定了，谢谢，我直接删掉重新fork了一个，今天刷300首没问题，感谢
