### ISSUE TITLE
每日触发会显示失败 大家有遇到过吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [secriy/CloudMusic-LevelUp#61]
![1](https://user-images.githubusercontent.com/12076232/126238910-69fbacd0-b458-4d20-bd23-1f2a947697fd.png)

部署到云函数  看了下日志  调用显示失败

**Comment by Yakumo-Yukari** [comment]
部署和测试都正常的 就是每天这个触发出问题了

**Comment by Secriy** [comment]
@Yakumo-Yukari 您好，能否提供下具体的日志和配置呢，不清楚的话可以通过邮箱或者微信联系。

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari 您好，能否提供下具体的日志和配置呢，不清楚的话可以通过邮箱或者微信联系。

我把配置和 日志 附件  发到你邮箱里了

**Comment by matocool** [comment]
你看下你的版本，一定要用1.0.3   1.0.0的版本就会这样。

1.0.3的版本我就有过一次跟你一样的问题。但是已经很久没有过了。

**Comment by Yakumo-Yukari** [comment]
> 你看下你的版本，一定要用1.0.3 1.0.0的版本就会这样。
> 
> 1.0.3的版本我就有过一次跟你一样的问题。但是已经很久没有过了。

哦哦  他这个版本在哪里看呢？
