### ISSUE TITLE
可以增加一个钉钉机器人推送吗？🙏🏻🙏🏻🙏🏻

### ISSUE THREAD

**Issue by 1489185654** [secriy/CloudMusic-LevelUp#66]

**Comment by secriy** [comment]
@1489185654 你好，稍后加入。

**Comment by 1489185654** [comment]
> @1489185654你好，稍后加入。

感谢感谢！！

**Comment by secriy** [comment]
@1489185654 你好已经加入，请严格按照[README](https://github.com/secriy/CloudMusic-LevelUp#%E9%92%89%E9%92%89%E6%9C%BA%E5%99%A8%E4%BA%BA%E6%8E%A8%E9%80%81)文档进行操作，如有问题烦请告知。
