### ISSUE TITLE
设置了DING_TOKEN之后 显示这个 

### ISSUE THREAD

**Issue by 1489185654** [secriy/CloudMusic-LevelUp#68]
![Screenshot_20210729_071632](https://user-images.githubusercontent.com/83204053/127409049-d1bf8f0e-40f2-4135-9270-8951734e22a0.jpg)
这是为啥啊？

**Comment by secriy** [comment]
@1489185654 上面显示token不存在，你再去复制一下那个机器人的token，记住只需要最后一段。

**Comment by 1489185654** [comment]
> @1489185654 上面显示token不存在，你再去复制一下那个机器人的token，记住只需要最后一段。

我重新设置了一下 还是不行

**Comment by secriy** [comment]
@1489185654 可以发一下联系方式，我邮箱：me@secriy.com

**Comment by 1489185654** [comment]
> @1489185654 可以发一下联系方式，我邮箱：[me@secriy.com](mailto:me@secriy.com)

👆🏻这个就是我QQ
