### ISSUE TITLE
你好，腾讯云函数部署版本是不是没有加入QMSG的推送功能呀 

### ISSUE THREAD

**Issue by immochan** [secriy/CloudMusic-LevelUp#70]
你好，腾讯云函数部署版本是不是没有加入QMSG的推送功能呀 
![image](https://user-images.githubusercontent.com/37736378/127621371-978e479f-0c3b-4f44-a611-ef47cae8fcaa.png)

**Comment by secriy** [comment]
@immochan 需要把最新版的代码复制过去的。

**Comment by immochan** [comment]
噢噢好的有看到，我还想着仿着加的哈哈
谢谢啦，很好用！很赞！
