### ISSUE TITLE
目前部署的腾讯云函数版本，发现刷歌的数量基本没有减少

### ISSUE THREAD

**Issue by immochan** [secriy/CloudMusic-LevelUp#71]
RT，是因为API失效吗，之前有部署过其他项目，也是API失效后无法使用

**Comment by secriy** [comment]
@immochan 这个项目我一直维护，并没有失效。
目前刷歌的歌单来源有两个：

- 网易云推荐歌单
- 用户收藏的歌单

前者会从中取320首，后者会从中取200首，当网易云音乐给你推荐的歌曲是你已经听过的或刷过的，就不再计算这首。
因此可以尝试收藏一些没有听过的歌单，但由于刷歌会影响推荐，请自行判断是否适合。
脚本近期作了更新，请检查下是否是最新版本，如果不是可以复制新的代码部署到腾讯云函数。

**Comment by immochan** [comment]
好的谢谢，我尝试一下新增收藏歌单和检查脚本版本。
