### ISSUE TITLE
执行至271行的语句出错

### ISSUE THREAD

**Issue by gradendripar** [secriy/CloudMusic-LevelUp#80]
前面的任务都执行的没问题，到执行第271行语句的时候，报出了ValueError: Sample larger than population or is negative的错，看起来是参数小了，不知道怎么解决，望作者大大看到了解决一下

![image](https://user-images.githubusercontent.com/67825668/130489403-113b9aab-e862-43f8-8c72-18b89ae29fd2.png)

**Comment by secriy** [comment]
@gradendripar 你好，我看了下你的代码应该是挺久之前的，现在应该已经没有这个问题了，可以把仓库更新到最新版本来解决。
