### ISSUE TITLE
签到有效，刷歌无效

### ISSUE THREAD

**Issue by BrightMoonInner** [secriy/CloudMusic-LevelUp#82]
大佬您好，我是在腾讯云上使用的，发现：每天签到是成功的，但是刷歌没有实际效果，连续多天过后还是“距离升级还需听1831首歌 ”。请问可能是什么原因呢
![刷](https://user-images.githubusercontent.com/88758484/130733022-8b745f24-b279-414e-a588-84ce36725818.jpg)

**Comment by secriy** [comment]
@BrightMoonInner 请问脚本后半部分是否正常执行？目前还不清楚原因，正在排查，可以加群联系。

**Comment by BrightMoonInner** [comment]
> 
> 
> @BrightMoonInner 请问脚本后半部分是否正常执行？目前还不清楚原因，正在排查，可以加群联系。
后面都是类似这样的显示
![后面](https://user-images.githubusercontent.com/88758484/130788347-640d7ba6-925e-435b-bb14-4e42f967096e.jpg)
好的，谢谢大佬
