### ISSUE TITLE
Actions签到次数多了就把库禁用了

### ISSUE THREAD

**Issue by Kifranei** [secriy/CloudMusic-LevelUp#90]
rt，
![Screenshot_2021-09-05-10-07-21-249_com microsoft office outlook](https://user-images.githubusercontent.com/79257237/132112647-e44258f4-c62d-41ad-8977-e9705c6a3b72.jpg)
碰到这种情况是不是只能本地跑了

**Comment by secriy** [comment]
@Kifranei 已经移除 GitHub Actions 部署功能，如有需要可以改用腾讯云函数等服务，若有服务器也可采用服务器登录。

**Comment by Kifranei** [comment]
好的，谢谢了
